version: '3.8'  
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Jeteron
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: todo-app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: